console.log(true);
console.log(false);
console.log(!false);
console.log(!!false);
console.log("Pruebas con comparaciones con números");
console.log(3 > 4);
console.log(3 < 4);
console.log(4 == 4);
console.log(4 == 3);
console.log(4 >= 4);
console.log(4 <= 4);
console.log(4 != 4);
console.log(4 == (4 == 1));
console.log("Pruebas con NaN");
console.log(NaN == NaN);
console.log(4 == NaN);


console.log("Pruebas con true y false y signos | &");
console.log(true && true);
console.log(true && false);
console.log(true || true);
console.log(true || false);
console.log(false || !false);
console.log(false && !false);
console.log(true || !false);
console.log("pruebas true y false con números y palabras");
console.log(!(3>4) == true);
console.log("red" == "red" && !false);
console.log("red" == "blue");
console.log(("re" + "d") == "red" && !false);
console.log(123 == "123" && !false);
console.log("Prueba comparación Boolean y String");
console.log(!"algo");
console.log(!!"algo");
console.log(!"");
console.log("algo" == true);
console.log(!"algo" == true);
console.log(!!0);
console.log(!!123);

console.log("\n");
console.log("pruebas con null y undefined");
console.log(null == undefined);
console.log(null === undefined);
console.log(9 * null);
console.log(9 * undefined);
console.log(typeof(NaN));
console.log(typeof(123));
console.log(typeof("123"));
console.log(typeof(undefined));
console.log(typeof(null));
console.log(typeof(true));
console.log(typeof(console));
console.log(typeof(typeof(true)));
console.log(typeof(console.log));
